### ISSUE TITLE
undo-tree 0.7.1 released

### ISSUE THREAD

**Issue by cireu** [emacsorphanage/undo-tree#2]
The origin author or undo-tree, just release a new version of undo-tree.

- https://elpa.gnu.org/packages/undo-tree-0.7.el
- http://www.dr-qubit.org/undo-tree.html

You may need to sync with upstream.

**Comment by tarsius** [comment]
Yes yes, I am coming. :stuck_out_tongue_winking_eye:
Rebased.

**Comment by cireu** [comment]
There was https://github.com/emacsorphanage/undo-tree/issues/1 but I didn't see it. I'm sorry.
